
-- Create notificacoes table
CREATE TABLE IF NOT EXISTS public.notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    type VARCHAR(50) NOT NULL, -- 'client', 'consultant', 'admin'
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE public.notificacoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own notifications"
    ON public.notificacoes
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "System/Admins can insert notifications"
    ON public.notificacoes
    FOR INSERT
    WITH CHECK (true); -- Ideally restrict to service role or specific users, but for now allow insert

CREATE POLICY "Users can update their own notifications (mark as read)"
    ON public.notificacoes
    FOR UPDATE
    USING (auth.uid() = user_id);
